// Fixed container dimensions for consistent scaling
const CONTAINER_WIDTH = 650;
const CONTAINER_HEIGHT = 1200;

// Global scale factor - scale down all elements by 10%
const GLOBAL_SCALE = 0.9;

// Use container dimensions instead of viewport for consistent scaling
const SCREEN_WIDTH = CONTAINER_WIDTH;
const SCREEN_HEIGHT = CONTAINER_HEIGHT;

// Font sizes (percentage of screen height) - scaled down 10%
export const FONT_SIZES = {
  TITLE: SCREEN_HEIGHT * 0.045 * GLOBAL_SCALE,
  PLAY_BUTTON: SCREEN_HEIGHT * 0.11 * GLOBAL_SCALE,
  TARGET_NUMBER: SCREEN_HEIGHT * 0.17 * GLOBAL_SCALE,
  PLAY_BUTTON_TEXT: SCREEN_HEIGHT * 0.155 * GLOBAL_SCALE,
  DIFFICULTY_BUTTON: SCREEN_HEIGHT * 0.023 * GLOBAL_SCALE,
  DIFFICULTY_BUTTON_LEVELS: SCREEN_HEIGHT * 0.018 * GLOBAL_SCALE,
  DIFFICULTY_SUBTEXT: SCREEN_HEIGHT * 0.016 * GLOBAL_SCALE,
  HISTORY_TITLE: SCREEN_HEIGHT * 0.020 * GLOBAL_SCALE,
  SUBTEXT: SCREEN_HEIGHT * 0.015 * GLOBAL_SCALE,
  LEVEL_NUMBER: SCREEN_HEIGHT * 0.025 * GLOBAL_SCALE,
  BUTTON_TEXT: SCREEN_HEIGHT * 0.022 * GLOBAL_SCALE,
  OPERATION_SYMBOL: SCREEN_HEIGHT * 0.049 * GLOBAL_SCALE,
  DIGIT_TEXT: SCREEN_HEIGHT * 0.048 * GLOBAL_SCALE,
  SUCCESS_BANNER: SCREEN_HEIGHT * 0.059 * GLOBAL_SCALE,
  BODY_TEXT: SCREEN_HEIGHT * 0.018 * GLOBAL_SCALE, // Scaled down 10%
};

export const SPACING = {
  MARGIN_SMALL: SCREEN_HEIGHT * 0.003 * GLOBAL_SCALE,
  MARGIN_MEDIUM: SCREEN_HEIGHT * 0.02 * GLOBAL_SCALE,
  MARGIN_LARGE: SCREEN_HEIGHT * 0.037 * GLOBAL_SCALE,
  BANNER_MARGIN: 20 * GLOBAL_SCALE, // Consistent margin for all black banners
  CALCULATOR_DISPLAY_MARGIN: 20 * GLOBAL_SCALE, // Consistent margin for all calculator display boxes
  LEVEL_TILE_MARGIN: SCREEN_WIDTH * 0.02 * GLOBAL_SCALE,
  PADDING_SMALL: SCREEN_HEIGHT * 0.012 * GLOBAL_SCALE,
  PADDING_MEDIUM: SCREEN_HEIGHT * 0.015 * GLOBAL_SCALE,
  PADDING_LARGE: SCREEN_HEIGHT * 0.025 * GLOBAL_SCALE,
  PADDING_XLARGE: SCREEN_HEIGHT * 0.037 * GLOBAL_SCALE,
  CONTAINER_PADDING_HORIZONTAL: SCREEN_WIDTH * 0.053 * GLOBAL_SCALE,
  CONTAINER_PADDING_TOP: SCREEN_HEIGHT * 0.062 * GLOBAL_SCALE,
  // Single vertical spacing constant for all top/bottom padding and margins
  VERTICAL_SPACING: 9
};

// Button sizes - scaled down 10%
export const BUTTON_SIZES = {
  PLAY_BUTTON_WIDTH: SCREEN_WIDTH * 0.747 * GLOBAL_SCALE,
  PLAY_BUTTON_HEIGHT: SCREEN_HEIGHT * 0.123 * GLOBAL_SCALE,
  DIFFICULTY_BUTTON_WIDTH: SCREEN_WIDTH * 0.52 * GLOBAL_SCALE,
  DIFFICULTY_BUTTON_PADDING_VERTICAL: SCREEN_HEIGHT * 0.014 * GLOBAL_SCALE,
  DIFFICULTY_BUTTON_PADDING_HORIZONTAL: SCREEN_WIDTH * 0.05 * GLOBAL_SCALE,
  DIFFICULTY_BUTTON_MARGIN_BOTTOM: SCREEN_HEIGHT * 0.014 * GLOBAL_SCALE,
  DIGIT_BUTTON_SIZE: SCREEN_WIDTH * 0.171 * 0.75 * 0.95 * GLOBAL_SCALE, // Scaled down 25% then 5% more, then 10%
  DIGIT_BUTTON_MARGIN: SCREEN_WIDTH * 0.015 * GLOBAL_SCALE,
  OPERATION_BUTTON_SIZE: SCREEN_WIDTH * 0.1425 * 0.65 * GLOBAL_SCALE, // Scaled down 35% then 10%
  OPERATION_BUTTON_MARGIN: SCREEN_WIDTH * 0.021 * GLOBAL_SCALE,
  NAV_ARROW_SIZE: SCREEN_WIDTH * 0.1197 * 0.75 * GLOBAL_SCALE, // Scaled down 25% then 10%
  NAV_ARROW_BOTTOM: SCREEN_HEIGHT * 0.025 * GLOBAL_SCALE,
  NAV_ARROW_HORIZONTAL: SCREEN_WIDTH * 0.053 * GLOBAL_SCALE,
};

// Calculator display - scaled down 10%
export const CALCULATOR_DISPLAY = {
  WIDTH: SCREEN_WIDTH * 0.776 * GLOBAL_SCALE, // Reduced by 3% (0.8 * 0.97 = 0.776)
  HEIGHT: SCREEN_HEIGHT * 0.18 * GLOBAL_SCALE,
  PADDING_HORIZONTAL: SCREEN_WIDTH * 0.05 * GLOBAL_SCALE,
  PADDING_VERTICAL: SCREEN_HEIGHT * 0.015 * GLOBAL_SCALE,
  BORDER_RADIUS: SCREEN_HEIGHT * 0.012 * GLOBAL_SCALE,
  SHADOW_OFFSET: SCREEN_WIDTH * 0.011 * GLOBAL_SCALE,
};

// History box - scaled down 10%
export const HISTORY_BOX = {
  WIDTH: SCREEN_WIDTH * 0.828 * GLOBAL_SCALE, // Reduced by 10% (0.92 * 0.9 = 0.828)
  BORDER_RADIUS: SCREEN_HEIGHT * 0.020 * GLOBAL_SCALE,
  HEIGHT_EASY: ((SCREEN_HEIGHT * 0.015 * 2) + (3 * ((SCREEN_HEIGHT * 0.005 * 2) + (SCREEN_HEIGHT * 0.017 * 1.10))) + (SCREEN_HEIGHT * 0.008)) * GLOBAL_SCALE,
  HEIGHT_MEDIUM: ((SCREEN_HEIGHT * 0.015 * 2) + (4 * ((SCREEN_HEIGHT * 0.005 * 2) + (SCREEN_HEIGHT * 0.017 * 1.10))) + (SCREEN_HEIGHT * 0.008)) * GLOBAL_SCALE,
  HEIGHT_HARD: ((SCREEN_HEIGHT * 0.015 * 2) + (5 * ((SCREEN_HEIGHT * 0.005 * 2) + (SCREEN_HEIGHT * 0.017 * 1.10))) + (SCREEN_HEIGHT * 0.012)) * GLOBAL_SCALE,
  BAR_BORDER_RADIUS: SCREEN_HEIGHT * 0.007 * GLOBAL_SCALE,
};

// Colors
export const COLORS = {
  BACKGROUND_LIGHT: '#f8f9fa',
  BACKGROUND_WHITE: '#fff',
  BACKGROUND_DARK: '#2C2C2C',
  BACKGROUND_DISABLED: '#E0E0E0',
  BACKGROUND_DISABLED_DARK: '#B0B0B0',
  BUTTON_BLUE: '#2196F3',
  BUTTON_BLUE_DARK: '#1976D2',
  BUTTON_BLUE_DARKER: '#0D47A1',
  DIGIT_FIRST_SELECTED: '#2196F3',
  DIGIT_SECOND_SELECTED: '#F44336',
  DIGIT_ERROR: '#D32F2F',
  DIFFICULTY_EASY: '#4CAF50',
  DIFFICULTY_MEDIUM: '#FF9800',
  DIFFICULTY_HARD: '#F44336',
  BUTTON_ORANGE: '#F57C00',
  BUTTON_ORANGE_DARK: '#E65100',
  TEXT_WHITE: '#FFFFFF',
  TEXT_BLACK: '#000000',
  TEXT_PRIMARY: '#2c3e50',
  TEXT_SECONDARY: '#333',
  TEXT_TERTIARY: '#333333',
  TEXT_SUCCESS: '#4CAF50',
  TEXT_DISABLED: '#9E9E9E',
  SHADOW_BLACK: '#000000',
};

// Border
export const BUTTON_BORDER = {
  WIDTH: 2,
  COLOR: '#000000',
};

export const BORDER_RADIUS = {
  SMALL: 4 * GLOBAL_SCALE,
  MEDIUM: 8 * GLOBAL_SCALE,
  LARGE: 12 * GLOBAL_SCALE,
  XLARGE: 20 * GLOBAL_SCALE,
};

export const SCREEN_DIMENSIONS = {
  WIDTH: SCREEN_WIDTH,
  HEIGHT: SCREEN_HEIGHT,
};

// Ad banner space (standard AdMob banner height is 50px)
export const AD_BANNER_HEIGHT = 50;

// Letter spacing - scaled down 10%
export const LETTER_SPACING = {
  TIGHT: SCREEN_WIDTH * 0.003 * GLOBAL_SCALE,
  NORMAL: SCREEN_WIDTH * 0.005 * GLOBAL_SCALE,
  WIDE: SCREEN_WIDTH * 0.011 * GLOBAL_SCALE,
  EXTRA_WIDE: SCREEN_WIDTH * 0.011 * GLOBAL_SCALE,
};

// Shadow offsets
export const SHADOW_OFFSETS = {
  STANDARD: { width: SCREEN_WIDTH * 0.011, height: SCREEN_HEIGHT * 0.005 },
  STANDARD_ALT: { width: 4, height: 4 },
  CIRCULAR: { width: 2.7, height: 2.7 },
  DIFFICULTY: { width: 4.4, height: 4.4 },
  ZERO: { width: 0, height: 0 },
  VERTICAL_SMALL: { width: 0, height: 2 },
  VERTICAL_MEDIUM: { width: 0, height: 4 },
};

// Animation values
export const ANIMATION = {
  SCALE_PRESSED: 0.92,
  SCALE_PRESSED_LIGHT: 0.95,
  SCALE_PRESSED_TAB: 0.98,
  SCALE_NORMAL: 1,
  TRANSLATE_X_PRESSED: 4,
  TRANSLATE_X_PRESSED_LIGHT: 2,
  TRANSLATE_X_PRESSED_TAB: 1,
  TRANSLATE_X_PRESSED_PLAY: 4,
  TRANSLATE_X_NORMAL: 0,
  TRANSLATE_X_SELECTED: 4,
  TRANSLATE_Y_PRESSED: 4,
  TRANSLATE_Y_PRESSED_LIGHT: 2,
  TRANSLATE_Y_PRESSED_TAB: 1,
  TRANSLATE_Y_PRESSED_PLAY: 4,
  TRANSLATE_Y_NORMAL: 0,
  TRANSLATE_Y_SELECTED: 4,
  DURATION_FAST: 100,
  TENSION: 300,
  FRICTION: 10,
  OPACITY_FULL: 1,
  OPACITY_HIDDEN: 0,
  OPACITY_DISABLED: 0.5,
  OPACITY_SUBTEXT: 0.9,
  OPACITY_SHADOW_LIGHT: 0.1,
  OPACITY_SHADOW_MEDIUM: 0.3,
  OPACITY_SHADOW_FULL: 0.5,
  INTERPOLATION_INPUT: [0, 1],
  INTERPOLATION_OUTPUT: [0, 1],
};

// Elevation values
export const ELEVATION = {
  NONE: 0,
  SMALL: 2,
  MEDIUM: 4,
  LARGE: 8,
};

// Padding values
export const PADDING_VALUES = {
  ZERO: 0,
  TAB_VERTICAL: 12,
  TAB_BORDER: 3,
  TAB_MARGIN_BOTTOM: -2,
};

// Numeric constants
export const NUMERIC_CONSTANTS = {
  FONT_MULTIPLIER_FULL: 1.0,
  FONT_MULTIPLIER_TAB: 0.78,
  FONT_MULTIPLIER_NAV_ARROW: 1.404,
  FONT_MULTIPLIER_TITLE: 0.93,
  DIVIDE_BY_2: 2,
  POSITION_TOP: 0,
  POSITION_LEFT: 0,
  POSITION_RIGHT: 0,
  POSITION_BOTTOM: 0,
  OPACITY_FULL: 1,
  OPACITY_HALF: 0.5,
  OPACITY_NINETY: 0.9,
  SPACING_DIVISION_6: 6,
};

